version: '3.6'

services:
  postgres:
    container_name: fiapdb
    image: postgres:15.3-alpine3.18
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - fiap-network
  
  enderecos:
    build: ../fiap/fiap-enderecos-api
    ports:
      - "8080:8080"
    networks:
      - fiap-network

networks:
  fiap-network:
    driver: bridge

volumes:
  postgres:
